name: gdmnet
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=1.12.0
  - torchvision
  - torchaudio
  - cpuonly  # CPU版本，避免CUDA依赖问题
  - pip
  - pip:
    - torch-geometric>=2.1.0
    - transformers>=4.20.0
    - pytorch-lightning>=1.7.0
    - datasets>=2.0.0
    - numpy>=1.21.0
    - pandas>=1.3.0
    - PyYAML>=6.0
    - tensorboard>=2.8.0
    - wandb>=0.12.0
    - tqdm>=4.64.0
    - scikit-learn>=1.1.0
    - matplotlib>=3.5.0
    - seaborn>=0.11.0
