# Fixed Configuration - Correct Entity/Relation Counts
# Based on actual data analysis

seed: 42

model:
  bert_model_name: "bert-base-uncased"
  hidden_size: 768
  num_entities: 8  # 0-7 range (max is 6, so 8 classes total)
  num_relations: 4  # 0-3 range (max is 2, so 4 classes total)
  num_classes: 5   # 0-4 range for labels
  gnn_type: "rgcn"
  num_gnn_layers: 1
  num_reasoning_hops: 2
  fusion_method: "gate"
  learning_rate: 1e-4
  dropout_rate: 0.1

data:
  train_path: "data/hotpotqa_small_train_fixed.json"
  val_path: "data/hotpotqa_small_val_fixed.json"
  test_path: "data/hotpotqa_small_val_fixed.json"
  max_length: 256
  max_query_length: 32

training:
  max_epochs: 2
  batch_size: 4
  num_workers: 1
  accelerator: "cpu"
  devices: 1
  precision: 32
  gradient_clip_val: 1.0
  accumulate_grad_batches: 2
  val_check_interval: 1.0
  log_every_n_steps: 10
  checkpoint_dir: "checkpoints"
  early_stopping: false
  patience: 2

logging:
  type: "tensorboard"
  save_dir: "logs"
  name: "gdmnet-fixed"
