# Official HotpotQA Configuration for Google Colab
# Optimized for real Wikipedia-based multi-hop reasoning data

seed: 42

model:
  bert_model_name: "bert-base-uncased"
  hidden_size: 768
  num_entities: 8
  num_relations: 4
  num_classes: 5
  gnn_type: "rgcn"
  num_gnn_layers: 2
  num_reasoning_hops: 3
  fusion_method: "gate"
  learning_rate: 2e-5
  dropout_rate: 0.1

data:
  train_path: "data/hotpotqa_official_train.json"
  val_path: "data/hotpotqa_official_val.json"
  test_path: "data/hotpotqa_official_val.json"
  max_length: 512  # 保持512以处理长文档
  max_query_length: 64

training:
  max_epochs: 5
  batch_size: 4  # 适应GPU内存和长文档
  num_workers: 2
  accelerator: "gpu"
  devices: 1
  precision: 16  # 混合精度节省内存
  gradient_clip_val: 1.0
  accumulate_grad_batches: 2  # 等效批次大小8
  val_check_interval: 0.25  # 每1/4 epoch验证一次
  log_every_n_steps: 100
  checkpoint_dir: "checkpoints"
  early_stopping: true
  patience: 2  # 官方数据更容易过拟合

logging:
  type: "tensorboard"
  save_dir: "logs"
  name: "gdmnet-official-hotpotqa"
