data:
  max_length: 512  # 增加到512以适应HotpotQA长文档
  max_query_length: 64
  test_path: data/hotpotqa_official_val.json
  train_path: data/hotpotqa_official_train.json
  val_path: data/hotpotqa_official_val.json
logging:
  name: gdmnet-optimized
  save_dir: logs
  type: tensorboard
model:
  bert_model_name: bert-base-uncased
  dropout_rate: 0.1
  fusion_method: gate
  gnn_type: rgcn
  hidden_size: 768
  learning_rate: 2.0e-05
  num_classes: 5
  num_entities: 10
  num_gnn_layers: 2
  num_reasoning_hops: 3
  num_relations: 20
seed: 42
training:
  accelerator: cpu
  accumulate_grad_batches: 4
  batch_size: 1  # 减少到1因为序列长度增加到512
  checkpoint_dir: checkpoints
  devices: 1
  early_stopping: true
  gradient_clip_val: 1.0
  log_every_n_steps: 10
  max_epochs: 5
  num_workers: 2
  patience: 3
  precision: 32
  val_check_interval: 1.0
